### ISSUE TITLE
domain purchase

### ISSUE THREAD

**Issue by leadscloud** [eXamadeus-zz/godaddypy#11]
{'name': 'ApiError', 'message': 'End-user must read and consent to all of the following legal agreements: DNRA', 'code': 'INVALID_AGREEMENT_KEYS'}

**Comment by eXamadeus-zz** [comment]
was this when running Client.get_domain_schema()?

**Comment by eXamadeus-zz** [comment]
In version 2.0.0+ I am removing the domain purchase API templates.  Please see the latest release (2.0.1 as of now).
