### ISSUE TITLE
Non wheel installs are not working

### ISSUE THREAD

**Issue by eXamadeus-zz** [eXamadeus-zz/godaddypy#15]
A cyclical dependency is created from the godaddypy import in setup.py.

**Comment by AndreasLoow** [comment]
As I said in #14, I think this is because in `setup.py` you have `from godaddypy import __version__` which imports `godaddypy/__init__.py` which in turn imports `godaddypy/client.py` which in turn tries to import requests (which fails if requests isn't installed before installing godaddypy).

**Comment by eXamadeus-zz** [comment]
Yea, and it only shows when not installing the (preconfigured) binaries.  I'm pretty sure you hit the nail on the head.

Thanks again.

**Comment by eXamadeus-zz** [comment]
Thanks for the fix @AndreasLoow!
