### ISSUE TITLE
SSL Error api.godaddy.com doesn't match

### ISSUE THREAD

**Issue by jiveman** [eXamadeus-zz/godaddypy#19]
raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'api.godaddy.com' doesn't match either of 'developer.godaddy.com', 'www.developer.godaddy.com'

**Comment by jiveman** [comment]
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: hostname 'api.godaddy.com' doesn't match either of 'developer.godaddy.com', 'www.developer.godaddy.com'

fixed it by upgrading a few packages on Ubuntu. http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

**Comment by eXamadeus-zz** [comment]
Closing this as invalid, as it related to local package issues.
