### ISSUE TITLE
godaddypy 2.2.1 gives error: 'Account' object has no attribute '_delegate'.

### ISSUE THREAD

**Issue by gitmeister** [eXamadeus-zz/godaddypy#22]
Re-installing godaddypy 2.1.2 works fine.

**Comment by eXamadeus-zz** [comment]
Thanks.  Missed a change in my original commit.  Updating the tests to make sure that this gets caught next time.

**Comment by eXamadeus-zz** [comment]
See version 2.2.2 for fix.

**Comment by gitmeister** [comment]
Works great, Thanks!
