### ISSUE TITLE
ATTENTION - ACCOUNT IS LOCKED: New repo with the same old name

### ISSUE THREAD

**Issue by eXamadeus** [eXamadeus-zz/godaddypy#30]
Long story, but I had to make a new account.  I plan to continue supporting GoDaddyPy in my free time.  I was able to free up my old username and this locked account was renamed from `eXamadeus` to `eXamadeus-zz`.

The new repo: https://github.com/eXamadeus/godaddypy will host GoDaddyPy from now on.  I will update the PyPi index as well.

**Comment by eXamadeus** [comment]
If you have starred/followed this old repo (`https://github.com/eXamadeus-zz/godaddypy`) you may want to undo that as there will be no more updates to anything ending in `-zz`.  Please use the https://github.com/eXamadeus/godaddypy repo from here on out.

**Comment by eXamadeus-zz** [comment]
Again, this account is dead and `eXamadeus` without the `-zz` is all that will be supported from here on out.
