### ISSUE TITLE
[Solved] Not working (Test Key Issue)

### ISSUE THREAD

**Issue by ToppDev** [eXamadeus-zz/godaddypy#4]
Hello,

I did the following:

> from godaddypy import Client, Account
> my_acct = Account(api_key='key', api_secret='secret')
> client = Client(my_acct)
> client.get_domains()

The last command gives me an error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/godaddypy/client.py", line 73, in get_domains
>     data = self._get(url, headers=self._get_headers()).json()
>   File "/usr/lib/python2.7/site-packages/godaddypy/client.py", line 53, in _get
>     self._validate_response_success(resp)
>   File "/usr/lib/python2.7/site-packages/godaddypy/client.py", line 48, in _validate_response_success
>     raise BadResponse(response.json())
>   File "/usr/lib/python2.7/site-packages/godaddypy/client.py", line 160, in __init__
>     super(_args, *_kwargs)
> TypeError: super() takes at least 1 argument (0 given)

Did I do something wrong or is the code broken?

Hope you can help.

Edit: Sorry was a problem with the key. Had to make an production not a test key

**Comment by eXamadeus-zz** [comment]
Are you still having issues, or did you resolve the issue yourself?

**Comment by ToppDev** [comment]
I solved the issue myself. I made the mistake that i created a test key on GoDaddy.

Then I tried it with a product key and it worked. So I closed the Issue. You can remove it or leave it for people making the same mistake that I did.

**Comment by eXamadeus-zz** [comment]
Nah, it's fine.  I'll leave it.  Maybe it will help someone :+1:

**Comment by gitmeister** [comment]
Helped me!

PS: So what the hell are Test keys if they can't be used?

**Comment by eXamadeus-zz** [comment]
The following is all my assumptions.  I don't work for GoDaddy so I don't really know...

The test keys connect you do a "test" environment.  It's not a clone of your account.  It is basically a simulated account with nothing in it.  It can be used to check to make sure your rest endpoints are working, etc.
