### ISSUE TITLE
A-Record disappeared after running

### ISSUE THREAD

**Issue by Yveske82** [eXamadeus-zz/godaddypy#8]
At an average of once a day my A-Record disappears from the godaddy DNS settings. Between all ‘Update ended with no Exception.’ logs I always have once this error:

```
Response Data: {u'message': u'One or more of the given records is invalid', u'code':
u'INVALID_RECORDS', u'errors': [u'ARECORD @ None is not a valid IP address'], u'name':
u'_Class'}
```

I actually always notice it when I can’t reach my address and then have to login into godaddy, make a new A-Record and wait until it’s updated again (and then some more) before I can reach it again. The error is always once, I guess then it get’s deleted, and after that I get again the ‘Update ended with no Exception.’ messages like everything is running fine. This is the script I run:

```
#!/usr/bin/env python3

# Full package imports
import pif, sys

# Partial imports
from godaddypy import Client, Account

userAccount  = Account(api_key='key', api_secret='secret')
userClient   = Client(userAccount)
publicIP     = pif.get_public_ip('ident.me')

# Updates all domains all records
try:
    updateResult = userClient.update_ip(publicIP)
except:
    print(sys.exc_info()[1])
    sys.exit()

if updateResult is True:
    print('Update ended with no Exception.')

```

**Comment by eXamadeus-zz** [comment]
It looks like the Client is trying to save a publicIP of None.

try adding this right below the `publicIP = pif.get_public_ip('ident.me')` line...

```
if publicIP is None or publicIP is False:
    print('Unable to retrieve an IP from pif, exiting...')
    sys.exit()
```

and let me know if it's still happening.

**Comment by Yveske82** [comment]
I added the code and will test it a few days. I'll keep you updated.
Thanks a lot.

**Comment by trkadi** [comment]
I'll refresh my script too. :)

**Comment by Yveske82** [comment]
This seems to be working fine. I don't get any 'Unable to retrieve an IP from pif, exiting...' in my cron logs just the normal 'Update ended with no Exception.' But it was a daily problem which since I added your part of code hasn't come back. So I assume it's working now.
Thanks a lot.

**Comment by eXamadeus-zz** [comment]
Interesting.  I'm glad it's working now though!

I'm going to close this Issue for now.  Let me know if something comes up.

**Comment by dark-vex** [comment]
I have the same issue, the proposed solution was added to updateReccord.py ??
