### ISSUE TITLE
Delete A record

### ISSUE THREAD

**Issue by sidheshdivekar29** [eXamadeus-zz/godaddypy#9]
Hi,
Is there a way to delete an existing A record.
I could not find one, also tried setting ttl = 0 in client.put_a_records() but
that seem to have no effect.

**Comment by eXamadeus-zz** [comment]
Unfortunately, to my knowledge, GoDaddy does not expose a direct "delete" A record API call.  Possibly this API call with a blank A record...

https://developer.godaddy.com/doc#!/_v1_domains/recordReplace

I haven't tested this myself, but you could try to use `Client.put_a_records('some.domain', [])` and see what happens.  The put_a_records method wraps that recordReplace API call.

**Comment by sidheshdivekar29** [comment]
Hi eXamadeus,
My requirement is that I just want to delete a particular record.
Passing an empty list means i want to delete all records for given domain.

**Comment by eXamadeus-zz** [comment]
Ahh sorry, I misread your comment.  I guess you'd need to get them all and "put" back that list minus the one you want to delete.  You should be able to do that with the Client.

**Comment by sidheshdivekar29** [comment]
Hi eXamadeus,
Initially I only have @ A records. Then i add another A record and I see @ and new A record.
If the behavior which you mentioned was the case then my root itself would get overwritten.

In [16]: client.get_a_records(domain='net.com')
Out[16]: 
[{u'data': u'3.3.3.3', u'name': u'@', u'ttl': 600, u'type': u'A'},
 {u'data': u'1.1.1.1', u'name': u'abc-420', u'ttl': 3600, u'type': u'A'},
 {u'data': u'1.1.1.2', u'name': u'abc-421', u'ttl': 3600, u'type': u'A'}]

In [18]: client.put_a_records(domain='net.com', records=[{u'data': u'3.3.3.3', u'name': u'@', u'ttl': 600, u'type': u'A'}, {u'data': u'1.1.1.1', u'name': u'abc-420', u'ttl': 3600, u'type': u'A'},])

In [19]: client.get_a_records(domain='net.com')
Out[19]: 
[{u'data': u'3.3.3.3', u'name': u'@', u'ttl': 600, u'type': u'A'},
 {u'data': u'1.1.1.1', u'name': u'abc-420', u'ttl': 3600, u'type': u'A'},
 {u'data': u'1.1.1.2', u'name': u'abc-421', u'ttl': 3600, u'type': u'A'}]

**Comment by eXamadeus-zz** [comment]
I'm looking into a solution to this, as currently it doesn't look like my wrapper can use godaddy's API to actually delete a domain record.  Unfortunately, GoDaddy's API is not loading for me right now and Google doesn't have the page cached.

I'm going to add this under an enhancement and code it whenever the API comes back up...

**Comment by eXamadeus-zz** [comment]
Added with version 2.0.1

**Comment by sidheshdivekar29** [comment]
Will it be possible to take both hostname and ip-address/data in delete api. That way if there are two ip addresses belonging to a dns name and only one needs to be deleted then only corresponding A rec will be deleted.

**Comment by sidheshdivekar29** [comment]
I also noticed that if i add two records with different ip address.
abc.net 1.1.1.1
abc.net 2.2.2.2
Then only one record is seen. Ideally there should be 2 records on godaddy.
Update api should update existing record but put_a_record should insert second record ?

**Comment by eXamadeus-zz** [comment]
There is technically no "DELETE" functionality provided by the GoDaddy API.

You can implement that functionality with your own scripts now.  I have provided a new method `Client.replace_records(self, domain, records, record_type=None, name=None)`.  You should be able to use `Client.get_records` perform the desired manipulations and then use `Client.replace_records`.  I wrote a small semblance of the delete functionality already, but I don't want to tie myself to bettering the GoDaddy API too much.  That will end up being a full-time job :P

**Comment by sidheshdivekar29** [comment]
Agree with you. Thanks a lot for providing replace_records api.
I will take a look at it.

**Comment by schworak** [comment]
I could't find any delete either. I ended up using a REGEX after querying the entire set of records.
So basically, query the entire set of records, check for the entry matching the one you want to delete, then if found use preg_replace to set that entry to blank (removing it) and PUT the date back.

Since I wanted the entire record (every record) for a given host name I used this REGEX:

$regex="/{[^{]+\"".$hostname."\"[^}]+},{0,1}/i";

Then I used that in preg_match to see if it exists and if it does then I use the same regex in preg_replace with a PUT to delete it. 

Clearly, if you wanted a specific type of record you could just add that to the regex string.
